#  kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-0.8" --dry-run=client -o yaml
---
apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"aws-ebs-csi-driver"},"name":"ebs-csi-controller-sa","namespace":"kube-system"}}
    labels:
      app.kubernetes.io/name: aws-ebs-csi-driver
    name: ebs-csi-controller-sa
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"aws-ebs-csi-driver"},"name":"ebs-external-attacher-role"},"rules":[{"apiGroups":[""],"resources":["persistentvolumes"],"verbs":["get","list","watch","update","patch"]},{"apiGroups":[""],"resources":["nodes"],"verbs":["get","list","watch"]},{"apiGroups":["csi.storage.k8s.io"],"resources":["csinodeinfos"],"verbs":["get","list","watch"]},{"apiGroups":["storage.k8s.io"],"resources":["volumeattachments"],"verbs":["get","list","watch","update","patch"]}]}
    labels:
      app.kubernetes.io/name: aws-ebs-csi-driver
    name: ebs-external-attacher-role
  rules:
  - apiGroups:
    - ""
    resources:
    - persistentvolumes
    verbs:
    - get
    - list
    - watch
    - update
    - patch
  - apiGroups:
    - ""
    resources:
    - nodes
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - csi.storage.k8s.io
    resources:
    - csinodeinfos
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - storage.k8s.io
    resources:
    - volumeattachments
    verbs:
    - get
    - list
    - watch
    - update
    - patch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"aws-ebs-csi-driver"},"name":"ebs-external-provisioner-role"},"rules":[{"apiGroups":[""],"resources":["persistentvolumes"],"verbs":["get","list","watch","create","delete"]},{"apiGroups":[""],"resources":["persistentvolumeclaims"],"verbs":["get","list","watch","update"]},{"apiGroups":["storage.k8s.io"],"resources":["storageclasses"],"verbs":["get","list","watch"]},{"apiGroups":[""],"resources":["events"],"verbs":["list","watch","create","update","patch"]},{"apiGroups":["snapshot.storage.k8s.io"],"resources":["volumesnapshots"],"verbs":["get","list"]},{"apiGroups":["snapshot.storage.k8s.io"],"resources":["volumesnapshotcontents"],"verbs":["get","list"]},{"apiGroups":["storage.k8s.io"],"resources":["csinodes"],"verbs":["get","list","watch"]},{"apiGroups":[""],"resources":["nodes"],"verbs":["get","list","watch"]},{"apiGroups":["coordination.k8s.io"],"resources":["leases"],"verbs":["get","watch","list","delete","update","create"]}]}
    labels:
      app.kubernetes.io/name: aws-ebs-csi-driver
    name: ebs-external-provisioner-role
  rules:
  - apiGroups:
    - ""
    resources:
    - persistentvolumes
    verbs:
    - get
    - list
    - watch
    - create
    - delete
  - apiGroups:
    - ""
    resources:
    - persistentvolumeclaims
    verbs:
    - get
    - list
    - watch
    - update
  - apiGroups:
    - storage.k8s.io
    resources:
    - storageclasses
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - list
    - watch
    - create
    - update
    - patch
  - apiGroups:
    - snapshot.storage.k8s.io
    resources:
    - volumesnapshots
    verbs:
    - get
    - list
  - apiGroups:
    - snapshot.storage.k8s.io
    resources:
    - volumesnapshotcontents
    verbs:
    - get
    - list
  - apiGroups:
    - storage.k8s.io
    resources:
    - csinodes
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - nodes
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - get
    - watch
    - list
    - delete
    - update
    - create
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"aws-ebs-csi-driver"},"name":"ebs-csi-attacher-binding"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"ebs-external-attacher-role"},"subjects":[{"kind":"ServiceAccount","name":"ebs-csi-controller-sa","namespace":"kube-system"}]}
    labels:
      app.kubernetes.io/name: aws-ebs-csi-driver
    name: ebs-csi-attacher-binding
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: ebs-external-attacher-role
  subjects:
  - kind: ServiceAccount
    name: ebs-csi-controller-sa
    namespace: kube-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"aws-ebs-csi-driver"},"name":"ebs-csi-provisioner-binding"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"ebs-external-provisioner-role"},"subjects":[{"kind":"ServiceAccount","name":"ebs-csi-controller-sa","namespace":"kube-system"}]}
    labels:
      app.kubernetes.io/name: aws-ebs-csi-driver
    name: ebs-csi-provisioner-binding
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: ebs-external-provisioner-role
  subjects:
  - kind: ServiceAccount
    name: ebs-csi-controller-sa
    namespace: kube-system
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"aws-ebs-csi-driver"},"name":"ebs-csi-controller","namespace":"kube-system"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"ebs-csi-controller","app.kubernetes.io/name":"aws-ebs-csi-driver"}},"template":{"metadata":{"labels":{"app":"ebs-csi-controller","app.kubernetes.io/name":"aws-ebs-csi-driver"}},"spec":{"containers":[{"args":["--endpoint=$(CSI_ENDPOINT)","--logtostderr","--v=5"],"env":[{"name":"CSI_ENDPOINT","value":"unix:///var/lib/csi/sockets/pluginproxy/csi.sock"},{"name":"AWS_ACCESS_KEY_ID","valueFrom":{"secretKeyRef":{"key":"key_id","name":"aws-secret","optional":true}}},{"name":"AWS_SECRET_ACCESS_KEY","valueFrom":{"secretKeyRef":{"key":"access_key","name":"aws-secret","optional":true}}}],"image":"k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v0.8.0","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":5,"httpGet":{"path":"/healthz","port":"healthz"},"initialDelaySeconds":10,"periodSeconds":10,"timeoutSeconds":3},"name":"ebs-plugin","ports":[{"containerPort":9808,"name":"healthz","protocol":"TCP"}],"volumeMounts":[{"mountPath":"/var/lib/csi/sockets/pluginproxy/","name":"socket-dir"}]},{"args":["--csi-address=$(ADDRESS)","--v=5","--feature-gates=Topology=true","--enable-leader-election","--leader-election-type=leases"],"env":[{"name":"ADDRESS","value":"/var/lib/csi/sockets/pluginproxy/csi.sock"}],"image":"quay.io/k8scsi/csi-provisioner:v1.5.0","name":"csi-provisioner","volumeMounts":[{"mountPath":"/var/lib/csi/sockets/pluginproxy/","name":"socket-dir"}]},{"args":["--csi-address=$(ADDRESS)","--v=5","--leader-election=true"],"env":[{"name":"ADDRESS","value":"/var/lib/csi/sockets/pluginproxy/csi.sock"}],"image":"quay.io/k8scsi/csi-attacher:v2.2.0","name":"csi-attacher","volumeMounts":[{"mountPath":"/var/lib/csi/sockets/pluginproxy/","name":"socket-dir"}]},{"args":["--csi-address=/csi/csi.sock"],"image":"quay.io/k8scsi/livenessprobe:v2.1.0","name":"liveness-probe","volumeMounts":[{"mountPath":"/csi","name":"socket-dir"}]}],"nodeSelector":{"kubernetes.io/os":"linux"},"priorityClassName":"system-cluster-critical","serviceAccountName":"ebs-csi-controller-sa","tolerations":[{"operator":"Exists"}],"volumes":[{"emptyDir":{},"name":"socket-dir"}]}}}}
    labels:
      app.kubernetes.io/name: aws-ebs-csi-driver
    name: ebs-csi-controller
    namespace: kube-system
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: ebs-csi-controller
        app.kubernetes.io/name: aws-ebs-csi-driver
    template:
      metadata:
        labels:
          app: ebs-csi-controller
          app.kubernetes.io/name: aws-ebs-csi-driver
      spec:
        containers:
        - args:
          - --endpoint=$(CSI_ENDPOINT)
          - --logtostderr
          - --v=5
          env:
          - name: CSI_ENDPOINT
            value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: key_id
                name: aws-secret
                optional: true
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: access_key
                name: aws-secret
                optional: true
          image: k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v0.8.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          name: ebs-plugin
          ports:
          - containerPort: 9808
            name: healthz
            protocol: TCP
          volumeMounts:
          - mountPath: /var/lib/csi/sockets/pluginproxy/
            name: socket-dir
        - args:
          - --csi-address=$(ADDRESS)
          - --v=5
          - --feature-gates=Topology=true
          - --enable-leader-election
          - --leader-election-type=leases
          env:
          - name: ADDRESS
            value: /var/lib/csi/sockets/pluginproxy/csi.sock
          image: quay.io/k8scsi/csi-provisioner:v1.5.0
          name: csi-provisioner
          volumeMounts:
          - mountPath: /var/lib/csi/sockets/pluginproxy/
            name: socket-dir
        - args:
          - --csi-address=$(ADDRESS)
          - --v=5
          - --leader-election=true
          env:
          - name: ADDRESS
            value: /var/lib/csi/sockets/pluginproxy/csi.sock
          image: quay.io/k8scsi/csi-attacher:v2.2.0
          name: csi-attacher
          volumeMounts:
          - mountPath: /var/lib/csi/sockets/pluginproxy/
            name: socket-dir
        - args:
          - --csi-address=/csi/csi.sock
          image: quay.io/k8scsi/livenessprobe:v2.1.0
          name: liveness-probe
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
        nodeSelector:
          kubernetes.io/os: linux
        priorityClassName: system-cluster-critical
        serviceAccountName: ebs-csi-controller-sa
        tolerations:
        - operator: Exists
        volumes:
        - emptyDir: {}
          name: socket-dir
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"aws-ebs-csi-driver"},"name":"ebs-csi-node","namespace":"kube-system"},"spec":{"selector":{"matchLabels":{"app":"ebs-csi-node","app.kubernetes.io/name":"aws-ebs-csi-driver"}},"template":{"metadata":{"labels":{"app":"ebs-csi-node","app.kubernetes.io/name":"aws-ebs-csi-driver"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"eks.amazonaws.com/compute-type","operator":"NotIn","values":["fargate"]}]}]}}},"containers":[{"args":["node","--endpoint=$(CSI_ENDPOINT)","--logtostderr","--v=5"],"env":[{"name":"CSI_ENDPOINT","value":"unix:/csi/csi.sock"}],"image":"k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v0.8.0","livenessProbe":{"failureThreshold":5,"httpGet":{"path":"/healthz","port":"healthz"},"initialDelaySeconds":10,"periodSeconds":10,"timeoutSeconds":3},"name":"ebs-plugin","ports":[{"containerPort":9808,"name":"healthz","protocol":"TCP"}],"securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/var/lib/kubelet","mountPropagation":"Bidirectional","name":"kubelet-dir"},{"mountPath":"/csi","name":"plugin-dir"},{"mountPath":"/dev","name":"device-dir"}]},{"args":["--csi-address=$(ADDRESS)","--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)","--v=5"],"env":[{"name":"ADDRESS","value":"/csi/csi.sock"},{"name":"DRIVER_REG_SOCK_PATH","value":"/var/lib/kubelet/plugins/ebs.csi.aws.com/csi.sock"}],"image":"quay.io/k8scsi/csi-node-driver-registrar:v1.3.0","lifecycle":{"preStop":{"exec":{"command":["/bin/sh","-c","rm -rf /registration/ebs.csi.aws.com-reg.sock /csi/csi.sock"]}}},"name":"node-driver-registrar","volumeMounts":[{"mountPath":"/csi","name":"plugin-dir"},{"mountPath":"/registration","name":"registration-dir"}]},{"args":["--csi-address=/csi/csi.sock"],"image":"quay.io/k8scsi/livenessprobe:v2.1.0","name":"liveness-probe","volumeMounts":[{"mountPath":"/csi","name":"plugin-dir"}]}],"hostNetwork":true,"nodeSelector":{"kubernetes.io/os":"linux"},"priorityClassName":"system-node-critical","tolerations":[{"operator":"Exists"}],"volumes":[{"hostPath":{"path":"/var/lib/kubelet","type":"Directory"},"name":"kubelet-dir"},{"hostPath":{"path":"/var/lib/kubelet/plugins/ebs.csi.aws.com/","type":"DirectoryOrCreate"},"name":"plugin-dir"},{"hostPath":{"path":"/var/lib/kubelet/plugins_registry/","type":"Directory"},"name":"registration-dir"},{"hostPath":{"path":"/dev","type":"Directory"},"name":"device-dir"}]}}}}
    labels:
      app.kubernetes.io/name: aws-ebs-csi-driver
    name: ebs-csi-node
    namespace: kube-system
  spec:
    selector:
      matchLabels:
        app: ebs-csi-node
        app.kubernetes.io/name: aws-ebs-csi-driver
    template:
      metadata:
        labels:
          app: ebs-csi-node
          app.kubernetes.io/name: aws-ebs-csi-driver
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: eks.amazonaws.com/compute-type
                  operator: NotIn
                  values:
                  - fargate
        containers:
        - args:
          - node
          - --endpoint=$(CSI_ENDPOINT)
          - --logtostderr
          - --v=5
          env:
          - name: CSI_ENDPOINT
            value: unix:/csi/csi.sock
          image: k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v0.8.0
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          name: ebs-plugin
          ports:
          - containerPort: 9808
            name: healthz
            protocol: TCP
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /var/lib/kubelet
            mountPropagation: Bidirectional
            name: kubelet-dir
          - mountPath: /csi
            name: plugin-dir
          - mountPath: /dev
            name: device-dir
        - args:
          - --csi-address=$(ADDRESS)
          - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
          - --v=5
          env:
          - name: ADDRESS
            value: /csi/csi.sock
          - name: DRIVER_REG_SOCK_PATH
            value: /var/lib/kubelet/plugins/ebs.csi.aws.com/csi.sock
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.3.0
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - rm -rf /registration/ebs.csi.aws.com-reg.sock /csi/csi.sock
          name: node-driver-registrar
          volumeMounts:
          - mountPath: /csi
            name: plugin-dir
          - mountPath: /registration
            name: registration-dir
        - args:
          - --csi-address=/csi/csi.sock
          image: quay.io/k8scsi/livenessprobe:v2.1.0
          name: liveness-probe
          volumeMounts:
          - mountPath: /csi
            name: plugin-dir
        hostNetwork: true
        nodeSelector:
          kubernetes.io/os: linux
        priorityClassName: system-node-critical
        tolerations:
        - operator: Exists
        volumes:
        - hostPath:
            path: /var/lib/kubelet
            type: Directory
          name: kubelet-dir
        - hostPath:
            path: /var/lib/kubelet/plugins/ebs.csi.aws.com/
            type: DirectoryOrCreate
          name: plugin-dir
        - hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
          name: registration-dir
        - hostPath:
            path: /dev
            type: Directory
          name: device-dir
- apiVersion: storage.k8s.io/v1beta1
  kind: CSIDriver
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"storage.k8s.io/v1beta1","kind":"CSIDriver","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"aws-ebs-csi-driver"},"name":"ebs.csi.aws.com"},"spec":{"attachRequired":true,"podInfoOnMount":false}}
    labels:
      app.kubernetes.io/name: aws-ebs-csi-driver
    name: ebs.csi.aws.com
  spec:
    attachRequired: true
    podInfoOnMount: false
kind: List
metadata: {}
