apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://open-policy-agent.github.io/gatekeeper/charts
    targetRevision: 3.17.1
    helm:
      values: |
        replicas: 1
        controllerManager:
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
    chart: gatekeeper
  destination:
    namespace: gatekeeper-system
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
