---
apiVersion: v1
kind: Service
metadata:
  name: kad
  namespace: kad
spec:
  type: NodePort
  selector:
    app: kad
  ports:
  - protocol: TCP
    targetPort: 5000
    port: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kad
  namespace: kad
data:
  config.yml: |
    abc: 123
    password: datascript
  color: white
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kad-env
  namespace: kad
data:
  ENVA: A
  ENVB: B
  ENVC: C
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: kad
type: Opaque
data:
  username: YWRtaW4=
  password: d29ya3Nob3BTRA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kad
  namespace: kad
  finalizers:
  #- 6shore.net/kad-manual
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kad
  template:
    metadata:
      labels:
        app: kad
    spec:
      initContainers:
      - name: init-file
        image: docker.io/debian
        command: ["bash", "-c", "date | tee /data/init-$(date --iso-8601=seconds)"]
        volumeMounts:
        - name: data-storage
          mountPath: /data/
      containers:
      - name: app
        image: docker.io/tomkukral/kad
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        #command: ["/bin/kad", "--color", "$(COLOR)"]
        envFrom:
        - configMapRef:
            name: kad-env
        env:
        # static configuration from yaml
        - name: REDIS_SERVER
          value: redis:6379
        # configuration from downward API
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        # variable form configmap
        - name: COLOR
          valueFrom:
            configMapKeyRef:
              name: kad
              key: color
        # variables from secret
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: password
        volumeMounts:
        - name: config
          mountPath: /etc/kad/
        - name: data-storage
          mountPath: /data/
      volumes:
      - name: data-storage
        emptyDir:
        #persistentVolumeClaim:
        #  claimName: kad-data
      - name: config
        configMap:
          name: kad
          items:
          - key: config.yml
            path: config.yml
