apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: training-apps
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/tomkukral/kubernetes-examples
    targetRevision: HEAD
    path: training-apps
    helm:
      values: |
        clusters: 
        - c0
        - c1
        - c2
        - c3
        - c4
        - c5
        - c6
        kadApps: [4, 5]
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
   automated:
     prune: true
     selfHeal: true
   syncOptions:
   - Validate=true
   - CreateNamespace=true
