apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-
              spec:
                entrypoint: print-message
                arguments:
                  parameters:
                  - name: message
                    # the value will get overridden by event payload from test-dep
                    value: hello world
                templates:
                - name: print-message
                  serviceAccountName: argo
                  inputs:
                    parameters:
                    - name: message
                  container:
                    image: alpine
                    command: [sh, -c]
                    args: ["echo \"{{inputs.parameters.message}}\""]
          parameters:
            - src:
                dependencyName: test-dep
              dest: spec.arguments.parameters.0.value
