apiVersion: v1
kind: Pod
metadata:
  name: kad
spec:
  containers:
  - name: app
    image: docker.io/tomkukral/kad
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    ports:
    - containerPort: 5000
