# run test with:
# gator verify -v .
kind: Suite
apiVersion: test.gatekeeper.sh/v1alpha1
metadata:
  name: privileged
tests:
- name: privileged
  template: ../privileged_template.yml
  constraint: ../privileged_constraint.yml
  cases:
  - name: allowed
    object: allowed.yml
    assertions:
    - violations: no
  - name: denied
    object: denied.yml
    assertions:
    - violations: yes
