---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  #type: ClusterIP
  type: NodePort
  #type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-debug
spec:
  #type: ClusterIP
  type: NodePort
  #type: LoadBalancer
  selector:
    app: nginx
    debug: "yes"
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.21.4
          ports:
            - containerPort: 80
