apiVersion: batch/v1
kind: CronJob
metadata:
  name: etcd-backup
spec:
  concurrencyPolicy: Forbid
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: etcdctl
            image: k8s.gcr.io/etcd:3.5.0-0
            command:
            - /bin/sh
            - -c
            - etcdctl snapshot save /data/$(POD_NAME).db && etcdctl snapshot status --write-out=table /data/$(POD_NAME).db
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
            env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ETCDCTL_API
              value: "3"
            - name: ETCDCTL_ENDPOINTS
              value: https://ip-10-255-N-10.eu-central-1.compute.internal:2379
            - name: ETCDCTL_CACERT
              value: /etc/kubernetes/pki/etcd/ca.crt
            - name: ETCDCTL_KEY
              value: /etc/kubernetes/pki/apiserver-etcd-client.key
            - name: ETCDCTL_CERT
              value: /etc/kubernetes/pki/apiserver-etcd-client.crt
            volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /etc/kubernetes/pki/
              name: certs
              readOnly: true
          volumes:
          - name: certs
            hostPath:
              path: /etc/kubernetes/pki/
          - name: data
            persistentVolumeClaim:
              claimName: etcd-backup
