kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kad
  name: ro
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["list"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["list", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kad-view
  namespace: kad
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""
roleRef:
  kind: Role
  name: ro
  apiGroup: rbac.authorization.k8s.io
