kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:permissive
subjects:
- kind: ServiceAccount
  name: default
  namespace: kad
roleRef:
  kind: ClusterRole
  name: psp:permissive
  apiGroup: rbac.authorization.k8s.io
