apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubernetes-examples
spec:
  interval: 5m0s
  url: https://github.com/tomkukral/kubernetes-examples.git
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argocd
spec:
  interval: 5m0s
  prune: false
  sourceRef:
    kind: GitRepository
    name: kubernetes-examples
  path: ./argo/cd
  targetNamespace: argo
