apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: 3step
  serviceAccountName: argo
  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker.io/docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]

  - name: 3step
    steps:
    - - name: hello1
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "hello1"
    - - name: hello2a
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "hello2a"
      - name: hello2b
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "hello2b"
